version: '3.1'
services:
    db:
        image: mariadb:10.4
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql_data:/var/lib/mysql"
            - "./data/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
        environment:
            MYSQL_ROOT_PASSWORD: 000000
            MYSQL_DATABASE: postal_data
            MYSQL_USER: test
            MYSQL_PASSWORD: test